version: 2

builds:
  - id: "ragrep"
    main: ./cmd/ragrep
    binary: ragrep
    goos:
      - linux
    ldflags:
      - -X main.Version={{ if .IsSnapshot }}{{ .Version }}{{ else }}{{ .Tag }}{{ end }}

snapshot:
  version_template: "{{ .Version }}-devel+{{ .ShortCommit }}"

archives:
  - id: "ragrep"
    name_template: "ragrep_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: true

    files:
      - UNLICENSE

    ids: [ragrep]
    formats: [tar.gz]
